let answer=prompt("What is your favorite color?")
let color=[]
answer=prompt("First color?")
color.push(answer)
answer=prompt("Second color?")
color.push(answer)
answer=prompt("Third color?")
color.push(answer)
answer=prompt("Fourth color?")
color.push(answer)
answer=prompt("Fifth color?")
color.push(answer)
answer=prompt("Sixth color?")
color.unshift(answer)
color.pop()
console.log(color)
